version: "3"

services:
  cassandra:
    image: cassandra:5.0
    ports:
      - "19042:9042"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 10

  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cassandra-ruby-driver
    environment:
      - CASSANDRA_HOST=cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    command: bash -c "cd /cassandra-ruby-driver && gem install bundler:1.17.3 && bundle install --without development docs && bundle exec rake rspec"
