# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra:5.0
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'describe keyspaces'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsnappy-dev liblz4-dev
    # - name: Wait for Cassandra
    #   run: |
    #     echo "Waiting for Cassandra to be ready..."
    #     timeout 300 bash -c 'until cqlsh --connect-timeout=15 localhost 9042; do sleep 2; done'
    - name: Run tests
      env:
        CASSANDRA_HOST: localhost
      run: bundle exec rake rspec
